packages:
  - 'apps/*'
  - 'common'
  - 'libs/*'
  - 'libs/shared/*'
  - 'shared'
  - 'shared/*'
  - 'prisma-schemas/*'
  - 'prisma-clients/*'
  - 'libs/prisma-schemas/product-schema'
  - 'libs/prisma-clients/product-client'
  - 'libs/prisma-clients/analytics-client'
  - 'libs/prisma-schemas/analytics-schema'
  - 'libs/prisma-schemas/order-schema'
  - 'libs/prisma-clients/order-client'
  - 'libs/shared/components/*'
  - 'libs/prisma-schemas/chatting-schema'
  - 'libs/prisma-clients/chatting-client'
  - 'libs/prisma-schemas/logger-schema'
  - 'libs/prisma-clients/logger-client'
  - 'libs/prisma-schemas/notification-schema'
  - 'libs/prisma-clients/notification-client'
