apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: tec-shop
  labels:
    app: kafka-service
    app.kubernetes.io/name: kafka-service
    app.kubernetes.io/part-of: tec-shop
spec:
  type: ClusterIP
  selector:
    app: kafka-service
  ports:
    - name: tcp
      port: 6009
      targetPort: 6009
      protocol: TCP
