apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: tec-shop
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: tec-shop
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 6012
      targetPort: 6012
      protocol: TCP
