apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: tec-shop
  labels:
    app: product-service
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: tec-shop
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - name: tcp
      port: 6004
      targetPort: 6004
      protocol: TCP
