apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: tec-shop
  labels:
    app: recommendation-service
    app.kubernetes.io/name: recommendation-service
    app.kubernetes.io/part-of: tec-shop
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - name: tcp
      port: 6010
      targetPort: 6010
      protocol: TCP
