import './global.css';
import { Poppins } from 'next/font/google';
import { SecurityMonitor } from '../shared/components/SecurityMonitor';

export const metadata = {
  title: 'Tecshop - Admin',
  description: 'Generated by create-nx-workspace',
};

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`h-screen overflow-hidden bg-[#080E1A] font-sans antialiased ${poppins.variable}`}
      >
        <SecurityMonitor />
        {children}
      </body>
    </html>
  );
}
